# Generated by Django 4.0.4 on 2022-05-12 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='Тематика вопросов')),
            ],
            options={
                'verbose_name': 'Тематика вопроса',
                'verbose_name_plural': 'Список тематик',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Пользователь')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Вопрос')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание вопроса')),
                ('media_files', models.FileField(blank=True, null=True, upload_to='', verbose_name='Медиа-вложения')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.rubric')),
            ],
            options={
                'verbose_name': 'Тема вопроса',
                'verbose_name_plural': 'Темы вопросов',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name_comm', models.CharField(max_length=50, verbose_name='Пользователь-комментатор')),
                ('content_comm', models.TextField(blank=True, null=True, verbose_name='Текст комментария')),
                ('media_files_comm', models.FileField(blank=True, null=True, upload_to='', verbose_name='Медиа-вложения комментария')),
                ('published_comm', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации комментария')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.subjects')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-published_comm'],
            },
        ),
    ]
