# Generated by Django 4.0.4 on 2022-05-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=50, verbose_name='Пользователь')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('media_files', models.FileField(blank=True, null=True, upload_to='', verbose_name='Медиа-вложения')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание вопроса')),
                ('sent', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отправления сообщения')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Принято к исправлению')),
                ('fixed', models.BooleanField(default=False, verbose_name='Исправлено')),
            ],
            options={
                'verbose_name': 'Замечание/Предложение',
                'verbose_name_plural': 'Замечания/Предложения',
                'ordering': ['-sent'],
            },
        ),
    ]
